module.exports = {
  "ఆదికాండము": "GENESIS",
  "నిర్గమకాండము": "EXODUS",
  "లేవీయకాండము": "LEVITICUS",
  "సంఖ్యాకాండము": "NUMBERS",
  "ద్వితీయోపదేశకాండము": "DEUTERONOMY",
  "యెహోషువ": "JOSHUA",
  "న్యాయాధిపతులు": "JUDGES",
  "రూతు": "RUTH",
  "1 సమూయేలు": "1 SAMUEL",
  "2 సమూయేలు": "2 SAMUEL",
  "1 రాజులు": "1 KINGS",
  "2 రాజులు": "2 KINGS",
  "1 దినవృత్తాంతములు": "1 CHRONICLES",
  "2 దినవృత్తాంతములు": "2 CHRONICLES",
  "ఎజ్రా": "EZRA",
  "నెహెమ్యా": "NEHEMIAH",
  "ఎస్తేరు": "ESTHER",
  "యోబు": "JOB",
  "కీర్తనలు": "PSALMS",
  "సామెతలు": "PROVERBS",
  "ప్రసంగి": "ECCLESIASTES",
  "పరమగీతము": "SONG OF SOLOMON",
  "యెషయా": "ISAIAH",
  "యిర్మియా": "JEREMIAH",
  "విలాపవాక్యములు": "LAMENTATIONS",
  "యెహెజ్కేలు": "EZEKIEL",
  "దానియేలు": "DANIEL",
  "హోషేయ": "HOSEA",
  "యోవేలు": "JOEL",
  "ఆమోసు": "AMOS",
  "ఒబద్యా": "OBADIAH",
  "యోనా": "JONAH",
  "మీకా": "MICAH",
  "నహూము": "NAHUM",
  "హబక్కూకు": "HABAKKUK",
  "జెఫన్యా": "ZEPHANIAH",
  "హగ్గయి": "HAGGAI",
  "జెకర్యా": "ZECHARIAH",
  "మలాకీ": "MALACHI",
  "మత్తయి": "MATTHEW",
  "మార్కు": "MARK",
  "లూకా": "LUKE",
  "యోహాను": "JOHN",
  "అపొస్తలుల కార్యములు": "ACTS",
  "రోమీయులకు": "ROMANS",
  "1 కొరింథీయులకు": "1 CORINTHIANS",
  "2 కొరింథీయులకు": "2 CORINTHIANS",
  "గలతీయులకు": "GALATIANS",
  "ఎఫెసీయులకు": "EPHESIANS",
  "ఫిలిప్పీయులకు": "PHILIPPIANS",
  "కొలొస్సయులకు": "COLOSSIANS",
  "1 థెస్సలొనీకయులకు": "1 THESSALONIANS",
  "2 థెస్సలొనీకయులకు": "2 THESSALONIANS",
  "1 తిమోతికి": "1 TIMOTHY",
  "2 తిమోతికి": "2 TIMOTHY",
  "తీతుకు": "TITUS",
  "ఫిలేమోనుకు": "PHILEMON",
  "హెబ్రీయులకు": "HEBREWS",
  "యాకోబు": "JAMES",
  "1 పేతురు": "1 PETER",
  "2 పేతురు": "2 PETER",
  "1 యోహాను": "1 JOHN",
  "2 యోహాను": "2 JOHN",
  "3 యోహాను": "3 JOHN",
  "యూదా": "JUDE",
  "ప్రకటన గ్రంథము": "REVELATION"
};
